### ISSUE TITLE
Level design 1st draft

### ISSUE THREAD

**Issue by aomchanun** [nathapatt/cpe103-test-group-06#10]

**Comment by aomchanun** [comment]
![image](https://user-images.githubusercontent.com/110968511/189175450-9b1339e9-e3e9-4c52-b4e8-11f3e2363a48.jpeg)

**Comment by l3eluGA** [comment]
![level draft](https://user-images.githubusercontent.com/110966223/189267749-f31ceb9c-15db-48c6-81c8-6f04d3d252a8.jpeg)

**Comment by l3eluGA** [comment]
![level draft 2](https://user-images.githubusercontent.com/110966223/189278774-17bbded8-3360-4622-aae2-bba19de24f78.jpeg)

**Comment by santhod** [comment]
![ด่าน 1 2](https://user-images.githubusercontent.com/110962180/189377102-e3e69b6c-9ba0-48cf-bd03-bc0ce0781d03.png)

**Comment by santhod** [comment]
![ภูเขา หนาม](https://user-images.githubusercontent.com/110962180/189377967-aa4132bd-afed-478a-95d7-1dde3ec614d3.png)
![ไม่มีชื่อ (2000 × 864px)](https://user-images.githubusercontent.com/110962180/189377984-8308ef8c-561f-4b06-84a5-3676cbe21bea.png)
![อิฐ หนาม](https://user-images.githubusercontent.com/110962180/189378001-ee118d2a-4446-456f-9c53-b54a797e388f.png)
![ไม่มีชื่อ (2000 × 864px) (2)](https://user-images.githubusercontent.com/110962180/189378036-fa8be3e3-76bf-4f68-a725-03063730878e.png)
![ไม่มีชื่อ (2000 × 864px) (3)](https://user-images.githubusercontent.com/110962180/189378054-f26cfc9c-7fd3-468e-a220-6098d0dd3fab.png)
หนามของด่านนี้

**Comment by santhod** [comment]
![ด่าน 2 1](https://user-images.githubusercontent.com/110962180/189384414-61f61b53-1bea-4f39-ab39-9758fc985967.png)
![ด่าน 2 2](https://user-images.githubusercontent.com/110962180/189384428-ecdd4891-22d7-4f65-9f2d-47fe13e4d778.png)
ด่าน2

**Comment by santhod** [comment]
![ด่าน 2 1](https://user-images.githubusercontent.com/110962180/189384815-5b402ff3-e940-43cc-9e3d-6f487a5b15a6.png)
![2 2](https://user-images.githubusercontent.com/110962180/189384826-97642e3f-1e09-4546-8606-6a990af16a28.png)
ด่าน2

**Comment by santhod** [comment]
![ไม่มีชื่อ (2000 × 864px) (6)](https://user-images.githubusercontent.com/110962180/189384978-a0d04109-c00a-4565-9e2b-e7f743733241.png)
![ไม่มีชื่อ (2000 × 864px) (5)](https://user-images.githubusercontent.com/110962180/189384987-4cbf68cf-2a1a-4cdf-8a1a-86a3a86b0384.png)
![ไม่มีชื่อ (2000 × 864px) (4)](https://user-images.githubusercontent.com/110962180/189384988-0009dd59-d970-490e-a088-14318224b90f.png)
หนาม

**Comment by santhod** [comment]
[ดีไซน์ที่ไม่มีชื่อ (1).zip](https://github.com/nathapatt/cpe103-group-06/files/9537146/1.zip)

**Comment by santhod** [comment]
![3](https://user-images.githubusercontent.com/110962180/189397538-311c8057-48d1-47fd-89e7-fb1f3009d326.png)
![4](https://user-images.githubusercontent.com/110962180/189397555-09252479-a526-48b3-a1aa-4a78f5a41988.png)
![5](https://user-images.githubusercontent.com/110962180/189397568-2489dd2f-4c85-4991-96e3-ac93c4cc937a.png)
![6](https://user-images.githubusercontent.com/110962180/189397584-cf80d995-0467-4bba-94c1-38e7bcf81492.png)
![1](https://user-images.githubusercontent.com/110962180/189397594-7b4634d4-66ac-4367-bdf9-82ab6b5b6262.png)
![2](https://user-images.githubusercontent.com/110962180/189397602-f46b9224-a741-4471-bec4-c7085faa4622.png)
ด่าน3

**Comment by santhod** [comment]
![อิฐ หนาม](https://user-images.githubusercontent.com/110962180/189398215-99be20a5-783d-403b-87a1-bfecacbb0b75.png)
![หินหนามเลื่อน](https://user-images.githubusercontent.com/110962180/189398221-02ddd3f0-213f-43c1-a2ac-06ccccff26f2.png)
![ดีไซน์ที่ไม่มีชื่อ (1)](https://user-images.githubusercontent.com/110962180/189398262-aff4e71c-c730-44dd-a1d3-4390461157f7.png)
![ดีไซน์ที่ไม่มีชื่อ (2)](https://user-images.githubusercontent.com/110962180/189398274-e5a2b698-d95f-463a-b2ca-0b0a987ede22.png)
![ดีไซน์ที่ไม่มีชื่อ](https://user-images.githubusercontent.com/110962180/189398288-7b812eb0-a246-452c-b669-21c1d4da899c.png)

**Comment by nathapatt** [comment]
![1](https://user-images.githubusercontent.com/110949168/189428185-cd9df7d5-b134-49fb-83f5-0c6c8d2e8a0a.png)
![2](https://user-images.githubusercontent.com/110949168/189428248-1f22dad0-7a00-4ab7-8987-5662d8edcb5f.png)
![3](https://user-images.githubusercontent.com/110949168/189428302-4d8c7cf9-3675-4841-87df-e3b3e78d6227.png)
![4](https://user-images.githubusercontent.com/110949168/189428336-aa9d2e47-b6af-4c7e-a33a-757586a2c24f.png)

**Comment by santhod** [comment]
![ไม่มีชื่อ (2000 × 864px) (10)](https://user-images.githubusercontent.com/110962180/189530083-bf2261f8-cdb3-4eca-ac62-75751469d893.png)
![ไม่มีชื่อ (2000 × 864px) (9)](https://user-images.githubusercontent.com/110962180/189530088-3cfed41f-eb0c-4bbf-867b-766a30cd12f8.png)
![ไม่มีชื่อ (2000 × 864px) (7)](https://user-images.githubusercontent.com/110962180/189530091-79b958aa-221c-4982-9800-daa0873d3997.png)

**Comment by santhod** [comment]
![ไม่มีชื่อ (2000 × 864px) (8)](https://user-images.githubusercontent.com/110962180/189531730-165c49d8-c33b-4d7a-b8b7-35fe4573adc6.png)
![ไม่มีชื่อ (2000 × 864px) (11)](https://user-images.githubusercontent.com/110962180/189531737-89a177c5-bf94-4d90-ace7-8baf085bff86.png)
![ไม่มีชื่อ (2000 × 864px) (12)](https://user-images.githubusercontent.com/110962180/189531738-deb1b1da-6b62-4d51-858b-d2a3f762f5ad.png)
![ไม่มีชื่อ (2000 × 864px) (13)](https://user-images.githubusercontent.com/110962180/189531740-8c5d8b57-ef92-4196-bb4a-de5dd810fd1f.png)
![ไม่มีชื่อ (2000 × 864px) (14)](https://user-images.githubusercontent.com/110962180/189531742-a348ed89-ce7d-448c-b832-bbd206acff87.png)
![ไม่มีชื่อ (2000 × 864px) (16)](https://user-images.githubusercontent.com/110962180/189531749-1e4489f3-3a70-4c1b-a45a-7b931501529d.png)

**Comment by santhod** [comment]
![ไม่มีชื่อ (2000 × 864px) (17)](https://user-images.githubusercontent.com/110962180/189532969-0650e43a-f59a-4ecc-9192-a50239eb31d4.png)
![ไม่มีชื่อ (2000 × 864px) (15)](https://user-images.githubusercontent.com/110962180/189532977-f6225f5d-9da2-407f-8beb-85227a0c3485.png)
![พื้นหนาม](https://user-images.githubusercontent.com/110962180/189532987-30b63279-ad55-41a1-b804-a65f0b89d3fa.png)

**Comment by santhod** [comment]
![ไม่มีชื่อ (2000 × 864px) (20)](https://user-images.githubusercontent.com/110962180/189533312-59e6efff-ad60-418f-af20-d197cea38768.png)
![ไม่มีชื่อ (2000 × 864px) (19)](https://user-images.githubusercontent.com/110962180/189533316-5fe1d5e1-bed8-4c79-9505-7f44c708784e.png)
![ไม่มีชื่อ (2000 × 864px) (18)](https://user-images.githubusercontent.com/110962180/189533318-d07a1c2a-e43a-46e8-967b-d1787c3db070.png)

**Comment by santhod** [comment]
![ไม่มีชื่อ (2000 × 864px) (23)](https://user-images.githubusercontent.com/110962180/189534167-c65d76e9-e6f4-4913-bae9-978db8fefb45.png)
![ไม่มีชื่อ (2000 × 864px) (24)](https://user-images.githubusercontent.com/110962180/189534172-7cb46e8b-930a-4c01-b9c4-712d6a97d899.png)
![ไม่มีชื่อ (2000 × 864px) (25)](https://user-images.githubusercontent.com/110962180/189534175-d15f161a-25cf-4aa2-b6b2-b4de9617b772.png)
![ไม่มีชื่อ (2000 × 864px) (22)](https://user-images.githubusercontent.com/110962180/189534180-2f85c261-55f9-4bde-858d-5495325bf06d.png)
![ไม่มีชื่อ (2000 × 864px) (21)](https://user-images.githubusercontent.com/110962180/189534185-24f6b4f9-80b9-4df2-aa5f-de6c5576be8e.png)
![ไม่มีชื่อ (2000 × 864px) (27)](https://user-images.githubusercontent.com/110962180/189534191-7c45310e-1cf5-447d-98cb-52d460f40aea.png)

**Comment by santhod** [comment]
![ไม่มีชื่อ (2000 × 864px) (29)](https://user-images.githubusercontent.com/110962180/189534730-affc8f0d-1c8b-4afb-a5de-45d530ad3281.png)
![ไม่มีชื่อ (2000 × 864px) (28)](https://user-images.githubusercontent.com/110962180/189534741-f9693cc7-0c48-4059-bb87-029ab99b3863.png)
![พุ่มไม้หนาม](https://user-images.githubusercontent.com/110962180/189534745-16696095-ad8e-462f-bc9d-621dd8b3e27f.png)
![พื้นหนาม](https://user-images.githubusercontent.com/110962180/189534750-1c90cb9d-d81f-44fa-8915-866c49f53343.png)

**Comment by santhod** [comment]
![C](https://user-images.githubusercontent.com/110962180/189537512-43bcba56-a6e7-4f6c-9214-7be7acff1c8c.png)
![B](https://user-images.githubusercontent.com/110962180/189537514-bc61f7cd-d0f8-4d5f-9802-5885b6bb6336.png)
![D](https://user-images.githubusercontent.com/110962180/189537515-6a72b000-1397-4398-b4f8-b8e37236c887.png)
![F](https://user-images.githubusercontent.com/110962180/189537516-3d2d38dd-7b23-491b-a6cc-75be374ccb78.png)
![A](https://user-images.githubusercontent.com/110962180/189537518-4bc7f7b9-2c8d-4c5d-9eca-75308735eede.png)

**Comment by santhod** [comment]
![20](https://user-images.githubusercontent.com/110962180/189710278-dc89a851-6b57-4e33-8ab9-ca3aa5edf033.png)
![21](https://user-images.githubusercontent.com/110962180/189710285-c5212a3a-f585-429c-8e6f-49f4454131a8.png)
![ไม่มีชื่อ (2000 × 864px) (40)](https://user-images.githubusercontent.com/110962180/189710297-2141f4cc-f032-444d-b859-c71bdbeeccbb.png)
