### ISSUE TITLE
Testing level 1

### ISSUE THREAD

**Issue by aomchanun** [nathapatt/cpe103-test-group-06#15]

**Comment by aomchanun** [comment]
Test1 เดิน+กระโดด+ตรวจจับบล้อกหญ้า
https://scratch.mit.edu/projects/730839159

ฉากที่ 1
- มีบัค hitbox ตอนชน object จากด้านข้าง
- ตอนตกลงมาจากบล็อคลอยฟ้า มันไม่ respawn ให้ใหม่

**Comment by aomchanun** [comment]
https://scratch.mit.edu/projects/731465487/editor
เพิ่มระบบตายเกิด อุปสรรคหนาม เปลี่ยนฉาก

ฉากที่ 1
- ถ้ากด a จนไปซ้ายสุดจะรีฉากที่ 1 ใหม่ ทำให้หนามในฉากที่ 1 หายไป

ฉากที่ 3
- พอถึงฉากที่ 3 ฉากเริ่มไม่เปลี่ยนแล้ว

**Comment by nathapatt** [comment]
เพิ่มhitbox เจออุปสรรคแล้วตาย เพิ่มศัตรูขยับได้+เหยียบหัวเพื่อฆ่าศัตรูได้
https://scratch.mit.edu/projects/731879979
