### ISSUE TITLE
Testing level 2

### ISSUE THREAD

**Issue by aomchanun** [nathapatt/cpe103-test-group-06#17]

**Comment by aomchanun** [comment]
ฉากที่ 1
- มีบัคตรงลูกศรชี้ลง ตัวสไปรท์ติดลูกศรตอนจะกระโดดลง

**Comment by aomchanun** [comment]
ฉากที่ 5
- ตรงฉากดำๆบนท่อ ถ้าเรากระโดดขึ้นไปจะตายทั้งๆที่ไม่มีอะไร หนามก็ไม่โผล่ขึ้นมาหลังตาย

**Comment by l3eluGA** [comment]
https://scratch.mit.edu/projects/733493112/editor/ แก้บัคบ้างแล้วงับ ลองดูก่อน
