### ISSUE TITLE
Game Cover

### ISSUE THREAD

**Issue by aomchanun** [nathapatt/cpe103-test-group-06#18]

**Comment by nathapatt** [comment]
ทำหน้าmenu + pop up ตอนgameover + เก็บgrade + แก้Enermyเป็นกะโหลก + ท่าวิ่ง
https://scratch.mit.edu/projects/733269075

**Comment by nathapatt** [comment]
ทำระบบcheck pointเมื่อเก็บเกรด + เพิ่มจำนวนชีวิตที่จะgameover + เพิ่มพื้นหลังGradeปัจจุบันของเรา (อันนี้เป็นล่าสุดที่เราทำละ)
https://scratch.mit.edu/projects/733308365
