### ISSUE TITLE
Backdrop 1st draft

### ISSUE THREAD

**Issue by aomchanun** [nathapatt/cpe103-test-group-06#4]

**Comment by santhod** [comment]
![Uploading 304850304_406452451593338_8375027661596643232_n.jpg…]()

**Comment by santhod** [comment]
![304850304_406452451593338_8375027661596643232_n](https://user-images.githubusercontent.com/110962180/188492824-a687b8c0-7306-45aa-82f5-0c79a278519c.jpg)
