### ISSUE TITLE
Objects and props 1st draft

### ISSUE THREAD

**Issue by aomchanun** [nathapatt/cpe103-test-group-06#5]

**Comment by santhod** [comment]
![พุ่มไม้](https://user-images.githubusercontent.com/110962180/188489263-4641cbce-8f45-4d50-8e01-f77244d34a9b.png)
![ภูเขา](https://user-images.githubusercontent.com/110962180/188489271-8f6eb7ec-94b7-4438-8b72-ded7eb6f7027.png)
![อิฐ](https://user-images.githubusercontent.com/110962180/188489281-938bd21a-8a17-4aa4-a698-45e7e20fd0b4.png)

**Comment by santhod** [comment]
![คำถาม](https://user-images.githubusercontent.com/110962180/188492658-6ddf5e02-d437-4d84-a7d0-b1d5d06ba417.png)

**Comment by santhod** [comment]
object อันนี้ไม่มีพื้นหลังอยู่แล้วนะ

**Comment by santhod** [comment]
![พื้น](https://user-images.githubusercontent.com/110962180/188898288-eac11cf6-5dd5-4d4d-8462-fc2e455161d6.png)

**Comment by santhod** [comment]
![พุ่มไม้หนาม](https://user-images.githubusercontent.com/110962180/188947544-bdacac6e-c201-4c38-aa99-0e0f1d305ffb.png)
![อิฐ หนาม](https://user-images.githubusercontent.com/110962180/188947555-c5f39658-9bbb-4d67-8eea-e972ec617dee.png)
![ภูเขา หนาม](https://user-images.githubusercontent.com/110962180/188947556-75cd9037-a13f-42fa-8469-09ffe5ce9870.png)

**Comment by aomchanun** [comment]
![189377984-8308ef8c-561f-4b06-84a5-3676cbe21bea](https://user-images.githubusercontent.com/110968511/189531185-5c453a0e-0c4b-43ca-8512-31e86502d43e.png)
![189384978-a0d04109-c00a-4565-9e2b-e7f743733241](https://user-images.githubusercontent.com/110968511/189531186-762c52a3-a0ff-485a-9ca9-03ea5886f5fa.png)
![189398215-99be20a5-783d-403b-87a1-bfecacbb0b75](https://user-images.githubusercontent.com/110968511/189531189-6b97aa8e-a07b-4a88-a7ad-ef1ac28f7225.png)
![189398221-02ddd3f0-213f-43c1-a2ac-06ccccff26f2](https://user-images.githubusercontent.com/110968511/189531190-e9310ba1-d0cc-4e79-b38b-be5277ccfd85.png)
![189398288-7b812eb0-a246-452c-b669-21c1d4da899c](https://user-images.githubusercontent.com/110968511/189531192-1a02ab69-9975-43ae-9a75-277c5765f53e.png)
