### ISSUE TITLE
Basic background

### ISSUE THREAD

**Issue by aomchanun** [nathapatt/cpe103-test-group-06#6]

**Comment by santhod** [comment]
![image](https://user-images.githubusercontent.com/110962180/188849955-fa65ea41-f6a8-4d28-9d27-5a43cfcb90f2.jpeg)

**Comment by nathapatt** [comment]
> ![image](https://user-images.githubusercontent.com/110962180/188849955-fa65ea41-f6a8-4d28-9d27-5a43cfcb90f2.jpeg)

ขอเป็นแบบไม่มีบล้อคอิฐได้ป้ะ ขอแค่พื้นหลังกับดินอะ แต่อยากให้สีหญ้ากับสีใบไม้คนละสีกัน

**Comment by santhod** [comment]
![พื้นหลัง](https://user-images.githubusercontent.com/110962180/188890294-6cb4f369-3274-4e5c-8ebb-1f40fd58cee4.png)
โอเคไหม

**Comment by santhod** [comment]
![พื้นหลัง2](https://user-images.githubusercontent.com/110962180/188893107-6c0e9e3e-974d-40d1-a19b-52824769b201.png)

**Comment by aomchanun** [comment]
![IMG_0931](https://user-images.githubusercontent.com/110968511/188919647-5f80795b-5e2f-4005-8e6d-94cbe7873a21.png)
น่าจะหมายถึงประมาณนี้ ขอสีหญ้าเป็นสีเดียวไม่ก็เป็นดินเฉยๆไปเลย เพราะสไปรท์มันต้องตรวจจับสีถ้าจะเดินบนพื้น

**Comment by santhod** [comment]
![2](https://user-images.githubusercontent.com/110962180/188943900-c3cb89c3-8859-4b7b-b2a0-e09f766ecb44.png)

**Comment by santhod** [comment]
![image](https://user-images.githubusercontent.com/110962180/188948971-2ff14514-9483-4c90-a1a1-e49e2c00aada.png)

**Comment by aomchanun** [comment]
![189384815-5b402ff3-e940-43cc-9e3d-6f487a5b15a6](https://user-images.githubusercontent.com/110968511/189531230-a372ab61-bfb9-4629-903d-74c197bbdd58.png)
![189384826-97642e3f-1e09-4546-8606-6a990af16a28](https://user-images.githubusercontent.com/110968511/189531234-e16711be-a4c0-4206-b89f-9cdc95d68721.png)
